Repository Spell-Binder-V1/spellbinder_be, pull requests merged in 2023-09, with the labels that each got.

#4 1 service setup
  app/controllers/api/v0/collections_controller.rb
  app/facades/card_facade.rb
  app/facades/collection_facade.rb
  app/poros/card.rb
  app/services/magic_service.rb
  config/routes.rb
  spec/facades/card_facade_spec.rb
  spec/facades/collection_facade_spec.rb
Labels: enhancement

#5 Read me
  README.md
Labels: documentation

#8 completes get search
  app/controllers/api/v0/cards_controller.rb
  app/facades/card_facade.rb
  app/services/magic_service.rb
  config/routes.rb
  spec/facades/card_facade_spec.rb
  spec/requests/api/v0/cards/cards_search_spec.rb
Labels: enhancement

#10 Search refactor
  app/controllers/api/v0/cards_controller.rb
  app/controllers/api/v0/search_controller.rb
  app/controllers/application_controller.rb
  app/facades/card_facade.rb
  app/services/magic_service.rb
  config/routes.rb
  spec/requests/api/v0/search/search_cards_request_spec.rb
Labels: enhancement, refactor

#12 Db setup
  Gemfile
  Gemfile.lock
  app/facades/card_facade.rb
  app/facades/collection_facade.rb
  app/models/card.rb
  app/models/deck.rb
  app/models/deck_card.rb
  app/models/user.rb
  app/poros/card_poro.rb
  db/migrate/20230915213107_create_users.rb
  db/migrate/20230915213702_create_decks.rb
  db/migrate/20230915220331_cards.rb
  db/migrate/20230915221353_create_deck_cards.rb
  db/schema.rb
  spec/facades/card_facade_spec.rb
  spec/facades/collection_facade_spec.rb
  spec/factories/deck_cards.rb
  spec/factories/decks.rb
  spec/factories/users.rb
  spec/models/card_spec.rb
  spec/models/deck_card_spec.rb
  spec/models/deck_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#27 User auth
  Gemfile
  Gemfile.lock
  app/controllers/api/v0/users_controller.rb
  app/controllers/application_controller.rb
  app/facades/user_facade.rb
  app/models/user.rb
  app/poros/user_poro.rb
  app/serializers/user_serializer.rb
  config/routes.rb
  spec/models/user_spec.rb
  spec/requests/api/v0/users/users_request_spec.rb
Labels: enhancement

#28 updates: schema
  app/models/card.rb
  app/models/deck_card.rb
  db/migrate/20230916234415_drop_cards_table.rb
  db/schema.rb
  spec/models/card_spec.rb
  spec/models/deck_card_spec.rb
  spec/models/deck_spec.rb
Labels: refactor

#29 User auth
  app/controllers/api/v0/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/helpers/session_helper.rb
  app/models/user.rb
  app/serializers/success_serializer.rb
  config/environments/test.rb
  config/routes.rb
  spec/models/user_spec.rb
  spec/requests/api/v0/users/users_request_spec.rb
Labels: enhancement

#31 Create decks
  app/controllers/api/v0/decks_controller.rb
  app/controllers/application_controller.rb
  app/controllers/helpers/session_helper.rb
  app/facades/deck_facade.rb
  app/models/deck.rb
  app/services/magic_service.rb
  config/routes.rb
  db/migrate/20230915213702_create_decks.rb
  db/migrate/20230915220331_cards.rb
  db/migrate/20230915221353_create_deck_cards.rb
  db/migrate/20230916234415_drop_cards_table.rb
  db/migrate/20230917200123_add_cards_to_decks.rb
  db/schema.rb
  spec/requests/api/v0/decks/add_card_request_spec.rb
  spec/requests/api/v0/decks/decks_requests_spec.rb
  spec/requests/api/v0/decks/remove_card_request_spec.rb
Labels: enhancement

#32 Decks ALL
  app/controllers/api/v0/decks_controller.rb
  app/models/deck.rb
  spec/requests/api/v0/decks/decks_destroy_request_spec.rb
  spec/requests/api/v0/decks/decks_index_request_spec.rb
  spec/requests/api/v0/decks/decks_show_request_spec.rb
  spec/requests/api/v0/decks/decks_update_request_spec.rb
  spec/requests/api/v0/decks/remove_card_request_spec.rb
Labels: enhancement

#36 refactor search
  app/controllers/api/v0/search_controller.rb
  spec/requests/api/v0/search/search_cards_request_spec.rb
Labels: refactor
